### ISSUE TITLE
[Feature] integrate with file icon

### ISSUE THREAD

**Issue by DanSnow** [shinenic/a-tree#66]
**Is your feature request related to a problem? Please describe.**
I want file icon in tree view like this
![image](https://user-images.githubusercontent.com/5575082/143681882-e381fa6e-a6e9-4de2-b0ba-2c5d0102dc04.png)

**Describe the solution you'd like**
Could you integrate [file-icon-js](https://github.com/websemantics/file-icons-js) into this extension?

**Describe alternatives you've considered**

**Additional context**

**Comment by shinenic** [comment]
Cool, I will take a look.

**Comment by DanSnow** [comment]
I found the `file-icon-js` in [another extension](https://github.com/lvarayut/github-file-icons). Maybe we can try to find another one in other extension

**Comment by shinenic** [comment]
Hey @DanSnow ,
I just published the latest version with variant file icons,
enjoy yourself!

**Comment by DanSnow** [comment]
Thanks @shinenic
